{
 "title": "service",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,exported_job)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_route)"
    }
   },
   { "name": "log_level", "query": "error, warn, info, debug" }
  ]
 },
 "panels": [
  { "title": "Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{ exported_job=~\"$service\", http_route=~\"$http_route\" }[2m])) by (http_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{ exported_job=~\"$service\", http_route=~\"$http_route\"}[2m])) by (le, http_route, http_status_code))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_status_code=~\"[4|5]..\", exported_job=~\"$service\", http_route=~\"$http_route\"}[2m])) by (http_status_code, http_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({job=\"$service\"} |= `` | json | __error__=`` | level =~ `$log_level` [10s]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"$service\"} |= `` | json | line_format `{{.level}} | {{.job}} | {{.message}}`"
    }
   ]
  }
 ]
}